GET {{baseUrl}}/items?facilityId={{facilityId}}
Authorization: Bearer {{accessToken}}

###
GET {{baseUrl}}/items?facilityId={{facilityId}}
Authorization: Bearer {{accessToken}}

###
GET {{baseUrl}}/items
Authorization: Bearer {{accessToken}}
